### ISSUE TITLE
Container crashing

### ISSUE THREAD

**Issue by zorbaTheRainy** [McCloudS/subgen#105]
I am processing a very large directory and has started to error with the following

```
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
stdout
WARNING:libav.nsv:Could not find codec parameters for stream 1 (Audio: none (m[151][170]R / 0x52AA976D), 0 channels): unknown codec
stdout
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
stdout
Traceback (most recent call last):
stdout
  File "/subgen/launcher.py", line 168, in <module>
stdout
    main()
stdout
  File "/subgen/launcher.py", line 163, in main
stdout
    subprocess.run([f'{python_cmd}', '-u', 'subgen.py'], check=True)
stdout
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
stdout
    raise CalledProcessError(retcode, process.args,
stdout
subprocess.CalledProcessError: Command '['python3', '-u', 'subgen.py']' died with <Signals.SIGSEGV: 11>.
```

The relevant compose file portion (of a larger stack) is:

```
  subgen_translate:
    container_name: subgen_translate
    hostname: subgen_translate
    tty: true
    image: mccloud/subgen:latest
    environment:
       - "TRANSCRIBE_DEVICE=gpu"
       - "WHISPER_MODEL=large-v3"
       - "TRANSCRIBE_OR_TRANSLATE=translate"
       # - "FORCE_DETECTED_LANGUAGE_TO=da"
       # - "NAMESUBLANG=aa"
       - "NAMESUBLANG=en"
       - "CONCURRENT_TRANSCRIPTIONS=1"
       - "WHISPER_THREADS=4"
       - "MONITOR=1"
       - "TRANSCRIBE_FOLDERS=/tv"
       - "SKIPIFINTERNALSUBLANG=eng"
       - "UPDATE=1"
       # - "PLEXTOKEN=plextoken"
       # - "PLEXSERVER=http://plexserver:32400"
       # - "JELLYFINTOKEN=token here"
       # - "JELLYFINSERVER=http://jellyfin:8096"
       - "WEBHOOKPORT=9000"
       - "PROCADDEDMEDIA=True"
       - "PROCMEDIAONPLAY=False"
       - "WORD_LEVEL_HIGHLIGHT=False"
       - "DEBUG=True"
       - "USE_PATH_MAPPING=False"
       - "PATH_MAPPING_FROM=/tv"
       - "PATH_MAPPING_TO=/Volumes/TV"
       - "CLEAR_VRAM_ON_COMPLETE=True"
       - "MODEL_PATH=./models"
       - "UPDATE=False"
       - "APPEND=False"
       - "USE_MODEL_PROMPT=False"
       - "CUSTOM_MODEL_PROMPT="
       - "LRC_FOR_AUDIO_FILES=True"
       - "CUSTOM_REGROUP=cm_sl=84_sl=42++++++1"
    volumes:
       # - /mnt/920p/Incoming_Files/2_AutoPirate/2_Processing/subgen_late:/tv
       - /mnt/920p/Multimedia/Videos/Movies:/tv
       - /docker/subgen/models:/subgen/models
    ports:
       - "9101:9000"
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```

OS info:

```
Linux 6.1.0-21-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.90-1 (2024-05-03) x86_64 GNU/Linux
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
Docker version 25.0.5, build 5dc9bcc
```

Any thoughts on how to fix this or how can you add more debug info?
Thanks

**Comment by McCloudS** [comment]
This is outside my expertise.  The error isn’t getting thrown in subgen, but in subprocess.py…

Are you getting the error immediately during the queuing process?  Is it the very first file or somewhere else down the way?  I’d guess a permissions issue…

**Comment by zorbaTheRainy** [comment]
> This is outside my expertise. 

Fair enough.

If you you leave this open for a week or two, I'll try to debug it and report back.
After that time, assume I found nothing enlightening.

**Comment by McCloudS** [comment]
Oh, sorry, I didn’t see your edits after the fact.  If this fixes the issue, I can update it.  I wonder why some images cause it and not others.  I’ve ran it on my /home/ folder which has large amount of various file types and never encountered this.

**Comment by McCloudS** [comment]
Added: https://github.com/McCloudS/subgen/commit/59fa01afce3e7f8f4136a4b7760dd84b4c1aa55c

**Comment by zorbaTheRainy** [comment]
I think you put the 
```
            if has_image_extension(file_path):
                return False
```
lines too low

It should be
```
    try:
        if has_image_extension(file_path):
            return False
        with av.open(file_path) as container:
            return any(stream.type == 'audio' for stream in container.streams)
    except (av.AVError, UnicodeDecodeError):
        return False
```
That way it never trips the `av.open()` that causes the SegFault.

**Comment by McCloudS** [comment]
Greatly appreciate you double checking me.  Fixed!

**Comment by zorbaTheRainy** [comment]
I greatly appreciate your work on this project.

As you can tell I am using it extensively.

Thank you
