### ISSUE TITLE
Subgen doesn't work properly under Jellyfin.

### ISSUE THREAD

**Issue by 793740870** [McCloudS/subgen#140]
Hello Developer,
I'm using Docker Compose for the deployment and Jellyfin as the playback client.
Half a month ago, when I was using subgen, it worked when I opened the movie, but failed because it couldn't load the model.
Recently, I wanted to try again, but when I opened the movie, there was no new information in log, which is different from when I used it before.Below is the log output:

```
 ==========
 == CUDA ==
 ==========

CUDA Version 12.3.2

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license
A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

WARNING: The NVIDIA Driver was not detected.  GPU functionality will not be available.
   Use the NVIDIA Container Toolkit to start this container with GPU support; see
   https://docs.nvidia.com/datacenter/cloud-native/ .

subgen.env file not found. Please run prompt_and_save_env_variables() first.
Downloading subgen.py from GitHub branch main...
File downloaded successfully to subgen.py
Launching subgen.py
2024-11-26 15:19:20,307 INFO: Subgen v2024.11.29
2024-11-26 15:19:20,865 INFO: Starting Subgen with listening webhooks!
2024-11-26 15:19:20,865 INFO: Transcriptions are limited to running 2 at a time
2024-11-26 15:19:20,865 INFO: Running 3 threads per transcription
2024-11-26 15:19:20,865 INFO: Using cpu to encode
2024-11-26 15:19:20,865 INFO: Using faster-whisper
[32mINFO[0m:     Started server process [[36m26[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[32mINFO[0m:     Uvicorn running on [1mhttp://0.0.0.0:9000[0m (Press CTRL+C to quit)
```

Here is my compose.yaml:

```
version: '2'
services:
  subgen:
    container_name: subgen
    tty: true
    image: mccloud/subgen
    environment:
     - "WHISPER_MODEL=medium" 
     - "WHISPER_THREADS=3" 
     - "PROCADDEDMEDIA=True" 
     - "PROCMEDIAONPLAY=True" 
     - "NAMESUBLANG=chi"
     - "SKIPIFINTERNALSUBLANG=chi" 
     - "SKIPIFEXTERNALSUB=True" 
     - "JELLYFINTOKEN=*"
     - "JELLYFINSERVER=http://192.168.31.235:8096" 
     - "WEBHOOKPORT=9000" 
     - "CONCURRENT_TRANSCRIPTIONS=2" 
     - "WORD_LEVEL_HIGHLIGHT=False" 
     - "DEBUG=True" 
     - "USE_PATH_MAPPING=False" 
     - "FORCE_DETECTED_LANGUAGE_TO=zh"
     - "TRANSCRIBE_OR_TRANSLATE=transcribe" 
     - "TRANSCRIBE_DEVICE=cpu" 
     - "CLEAR_VRAM_ON_COMPLETE=True" 
     - "MODEL_PATH=./models" 
     - "UPDATE=True"
     - "APPEND=False" 
     - "USE_MODEL_PROMPT=True" 
     - "CUSTOM_MODEL_PROMPT=Hello, welcome to my lecture." 
     - "LRC_FOR_AUDIO_FILES=True" 
     - "CUSTOM_REGROUP=cm_sl=84_sl=42++++++1" 
     - "SUBGEN_KWARGS={'vad': True,'prefix': '对，没错，继续。'}"
    volumes:
     - /volume1/movie:/movie
     - /volume1/docker/subgen/models:/subgen/models 

    ports:
     - 9000:9000
   ```

Another question, I would like to know how to successfully download the model, but it did not provide any information for me to download from where?

**Comment by McCloudS** [comment]
Hi there, the model download is automatic when the transcription starts, no user intervention is necessary.  It downloads it via faster-whisper from https://huggingface.co/Systran

The newest Jellyfin image and Subgen image work just fine:

![image](https://github.com/user-attachments/assets/289b19e7-4f57-4a6c-8d87-55f1256491cd)

I would double check your webhook settings (from the readme) in Jellyfin and that it can route to your subgen container.  Additionally, making sure your api key matches what's in Jellyfin.

**Comment by 793740870** [comment]
Here is my webhook setting:

![192 168 31 235_8096_web](https://github.com/user-attachments/assets/aff5088c-b1fc-4aab-8bac-acb7fbe62755)

The API key is entered correctly.
I use Jellyfin image as Nyanmisaka/Jellyfin,
Server version 10.10.0
Web version 10.10.0
Build version 241027
The webhook version is 15.0.0.0

**Comment by McCloudS** [comment]
If you see zero output in subgen logs when you play or add a file in Jellyfin, then the Jellyfin container isn’t contacting subgen for some reason.  You should at least see something in the logs, even if your API key is wrong.

**Comment by 793740870** [comment]
Oh, I think I found the problem: uncheck the user filter of the webhook, and it will work.

**Comment by McCloudS** [comment]
Great, all good now?

**Comment by 793740870** [comment]
Here is the log output:
```
2024-11-27 04:16:59,479 DEBUG: Model was purged, need to re-create
2024-11-27 04:17:03,290 INFO: Metadata refresh queued successfully.
2024-11-27 04:17:03,290 INFO: Metadata for item 261ec3f60e238f4c7627df556c2bec refreshed successfully.
[32mINFO[0m:     172.21.0.1:47940 - "[1mPOST /jellyfin HTTP/1.1[0m" [32m200 OK[0m
2024-11-27 04:19:16,933 WARNING: An error occured while synchronizing the model Systran/faster-whisper-medium from the Hugging Face Hub:

```

**Comment by McCloudS** [comment]
Does the container not have access to the Internet or huggingface?  The error seems to imply that.

**Comment by 793740870** [comment]
I tried to add `HTTP-PROXY` and `HTTPs_PROXY` environment variables to subgen
Here is the log output:
```

2024-11-27 05:48:09,042 DEBUG: itemid is: **
[32mINFO[0m:     172.21.0.1:49556 - "[1mPOST /jellyfin HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     172.21.0.1:49496 - "[1mPOST /jellyfin HTTP/1.1[0m" [91m500 Internal Server Error[0m
[31mERROR[0m:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 214, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.10/dist-packages/starlette/concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "/subgen/subgen.py", line 276, in receive_jellyfin_webhook
    fullpath = get_jellyfin_file_name(ItemId, jellyfinserver, jellyfintoken)
  File "/subgen/subgen.py", line 715, in get_jellyfin_file_name
    users = json.loads(requests.get(f"{jellyfin_url}/Users", headers=headers).content)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```
Can we have other ways to access the Internet or huggingface?like #97 ?But I don't know how to operate it

**Comment by McCloudS** [comment]
Proxy variables are outside the scope of subgen, but I can provide what directory structure you need to manually download and run the models.

**Comment by 793740870** [comment]
Okay, thank you. I'm waiting for your reply!

**Comment by McCloudS** [comment]
To give you an idea of what the structure should look like if you try to manually clone the hugging face models: 
![image](https://github.com/user-attachments/assets/753bd862-0b19-4416-b19b-2a0b5934d24c)

The folder would go in your mounted models directory.

**Comment by 793740870** [comment]
Thank you very much for your prompt. It seems to be working properly now. But its steps are a bit cumbersome, so can we add proxy variables to simplify the operation?

```

2024-11-28 12:01:16,797 INFO: Transcription of test.mp4 is completed, it took 6 m
inutes and 11 seconds to complete.

```

**Comment by McCloudS** [comment]
Outside the scope of this effort.  You could always use a different container like gluetun.

The instructions assume the container has access to the Internet.
