### ISSUE TITLE
Error: File "/subgen/subgen.py", line 731, in get_audio_tracks

### ISSUE THREAD

**Issue by CyberBlaed** [McCloudS/subgen#145]
Seems to be an error occured by today... (latest Dec 1 Change)
- (I have it set to 'true' went back to 'false' and the error kept occuring, nuked the docker image and pulled fresh with 'false' and same error.)

https://github.com/McCloudS/subgen/blob/3ad1a76c757c0f428b4984dade4e1d8958b5bd6d/subgen.py#L731

Output:

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

subgen.env file not found. Please run prompt_and_save_env_variables() first.
subgen.py exists and UPDATE is set to False, skipping download.

Launching subgen.py
INFO:root:Subgen v2024.11.32
INFO:root:Starting Subgen with listening webhooks!
INFO:root:Transcriptions are limited to running 2 at a time
INFO:root:Running 4 threads per transcription
INFO:root:Using cuda to encode
INFO:root:Using faster-whisper
INFO:root:Starting to search folders to see if we need to create subtitles.

Traceback (most recent call last):
  File "/subgen/subgen.py", line 731, in get_audio_tracks
    probe = ffmpeg.probe(video_file, select_streams='a')
AttributeError: module 'ffmpeg' has no attribute 'probe'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/subgen/subgen.py", line 1175, in <module>
    transcribe_existing(transcribe_folders)
  File "/subgen/subgen.py", line 1149, in transcribe_existing
    gen_subtitles_queue(path_mapping(file_path), transcribe_or_translate, forceLanguage)
  File "/subgen/subgen.py", line 798, in gen_subtitles_queue
    force_language = choose_transcribe_language(file_path, force_language)
  File "/subgen/subgen.py", line 670, in choose_transcribe_language
    audio_tracks = get_audio_tracks(file_path)
  File "/subgen/subgen.py", line 751, in get_audio_tracks
    except ffmpeg.Error as e:
AttributeError: module 'ffmpeg' has no attribute 'Error'. Did you mean: 'errors'?
Traceback (most recent call last):
  File "/subgen/launcher.py", line 170, in <module>
    main()
  File "/subgen/launcher.py", line 165, in main
    subprocess.run([f'{python_cmd}', '-u', 'subgen.py'], check=True)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python3', '-u', 'subgen.py']' returned non-zero exit status 1.
~~End of error, Docker Closed~~

My work around was to use the older commit, point the docker folder to that and use that.

Git Commit; https://github.com/McCloudS/subgen/tree/d0333e2c012101685a5a132a0e85913dc689b223

Resolution
1. Download full repo comit at that time.
2. unpack, and point docker container at that folder (put that in /appdata/subgen and path into docker container as just "/subgen"
![Screenshot 2024-12-01 at 5 39 21 pm](https://github.com/user-attachments/assets/7ec1b850-786a-4fbb-9bc7-fcb057928910)
3. Worked fine as a result. :) (no idea how to fix it or what the error is, but an easy solution was just simply rollback in this case.

**Comment by lukyjay** [comment]
Same error here:

```
subgen.env file not found. Please run prompt_and_save_env_variables() first.
subgen.py exists and UPDATE is set to False, skipping download.
Launching subgen.py
2024-12-01 11:18:19,226 INFO: Subgen v2024.11.32
2024-12-01 11:18:19,226 INFO: Starting Subgen with listening webhooks!
2024-12-01 11:18:19,226 INFO: Transcriptions are limited to running 2 at a time
2024-12-01 11:18:19,226 INFO: Running 6 threads per transcription
2024-12-01 11:18:19,226 INFO: Using cpu to encode
2024-12-01 11:18:19,226 INFO: Using faster-whisper
2024-12-01 11:18:19,226 INFO: Starting to search folders to see if we need to create subtitles.
2024-12-01 11:18:19,226 DEBUG: The folders are:
2024-12-01 11:18:19,226 DEBUG: /pve1storage/Media/TV
2024-12-01 11:18:19,274 DEBUG: /pve1storage/Media/TV/New Girl (2011) [tvdbid-248682]/season07-poster.jpg is an image or is an invalid file or path (are your volumes correct?), skipping processing
2024-12-01 11:18:19,275 DEBUG: /pve1storage/Media/TV/New Girl (2011) [tvdbid-248682]/fanart.jpg is an image or is an invalid file or path (are your volumes correct?), skipping processing
2024-12-01 11:18:19,275 DEBUG: /pve1storage/Media/TV/New Girl (2011) [tvdbid-248682]/banner.jpg is an image or is an invalid file or path (are your volumes correct?), skipping processing
2024-12-01 11:18:19,275 DEBUG: /pve1storage/Media/TV/New Girl (2011) [tvdbid-248682]/season05-poster.jpg is an image or is an invalid file or path (are your volumes correct?), skipping processing
Traceback (most recent call last):
  File "/subgen/subgen.py", line 731, in get_audio_tracks
    probe = ffmpeg.probe(video_file, select_streams='a')
            ^^^^^^^^^^^^
AttributeError: module 'ffmpeg' has no attribute 'probe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/subgen/subgen.py", line 1175, in <module>
    transcribe_existing(transcribe_folders)
  File "/subgen/subgen.py", line 1149, in transcribe_existing
    gen_subtitles_queue(path_mapping(file_path), transcribe_or_translate, forceLanguage)
  File "/subgen/subgen.py", line 798, in gen_subtitles_queue
    force_language = choose_transcribe_language(file_path, force_language)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/subgen/subgen.py", line 670, in choose_transcribe_language
    audio_tracks = get_audio_tracks(file_path)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/subgen/subgen.py", line 751, in get_audio_tracks
    except ffmpeg.Error as e:
           ^^^^^^^^^^^^
AttributeError: module 'ffmpeg' has no attribute 'Error'. Did you mean: 'errors'?
Traceback (most recent call last):
  File "/subgen/launcher.py", line 170, in <module>
    main()
  File "/subgen/launcher.py", line 165, in main
    subprocess.run([f'{python_cmd}', '-u', 'subgen.py'], check=True)
  File "/usr/local/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python3', '-u', 'subgen.py']' returned non-zero exit status 1.
```

**Comment by muisje** [comment]
I can't check it right now, but i think python-ffmpeg needs to be replaced with ffmpeg-python in requirements.txt

**Comment by McCloudS** [comment]
> I can't check it right now, but i think python-ffmpeg needs to be replaced with ffmpeg-python in requirements.txt

Yeah, that appears to be the issue.  I'll push the new docker images.  Sorry everyone, made some pretty substantial updates yesterday.  Might need to refactor back towards PyAV.
