### ISSUE TITLE
KeyError: 'transcribe_or_translate'

### ISSUE THREAD

**Issue by darinlarimore** [McCloudS/subgen#152]
Getting this error on some videos. I'm using the plex webhook.

```
Exception in thread Thread-1 (transcription_worker):
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "F:\subgen\subgen.py", line 138, in transcription_worker
    gen_subtitles(task['path'], task['transcribe_or_translate'], task['force_language'])
KeyError: 'transcribe_or_translate'
```

**Comment by McCloudS** [comment]
A longer log would be nice, but I may have fixed it.  UPDATE=True or pull the new subgen.py and let me know!

**Comment by darinlarimore** [comment]
Wow quick fix thank you! It works now! @McCloudS
