### ISSUE TITLE
ModuleNotFoundError: No module named 'watchdog'

### ISSUE THREAD

**Issue by Spillebulle** [McCloudS/subgen#80]
After a new image pull I get this error on :latest causing the container to stop

2024-04-09T17:50:18.254346388Z subgen.env file not found. Please run prompt_and_save_env_variables() first.
2024-04-09T17:50:18.254363974Z subgen.py exists and UPDATE is set to False, skipping download.
2024-04-09T17:50:18.254367378Z Launching subgen.py
2024-04-09T17:50:22.951462439Z Traceback (most recent call last):
2024-04-09T17:50:22.951493248Z   File "/subgen/subgen.py", line 27, in <module>
2024-04-09T17:50:22.951515086Z     from watchdog.observers.polling import PollingObserver as Observer
2024-04-09T17:50:22.951528023Z ModuleNotFoundError: No module named 'watchdog'
2024-04-09T17:50:23.652572367Z Traceback (most recent call last):
2024-04-09T17:50:23.652591512Z   File "/subgen/launcher.py", line 168, in <module>
2024-04-09T17:50:23.652930700Z     main()
2024-04-09T17:50:23.652938337Z   File "/subgen/launcher.py", line 163, in main
2024-04-09T17:50:23.652999429Z     subprocess.run([f'{python_cmd}', '-u', 'subgen.py'], check=True)
2024-04-09T17:50:23.653003860Z   File "/usr/lib/python3.10/subprocess.py", line 526, in run
2024-04-09T17:50:23.653637977Z     raise CalledProcessError(retcode, process.args,
2024-04-09T17:50:23.653642597Z subprocess.CalledProcessError: Command '['python3', '-u', 'subgen.py']' returned non-zero exit status 1.

**Comment by McCloudS** [comment]
I’ll rebuild the image and it should fix it.  Quick fix is try UPDATE=True which fixes the watchdog import.

**Comment by McCloudS** [comment]
Assuming you''re good now.  Reply if not.

**Comment by Spillebulle** [comment]
I added the UPDATE=True as an env but still same error message

**Comment by Spillebulle** [comment]
> Assuming you're good now. Reply if not.

I added the UPDATE=True as an env but still same error message

**Comment by McCloudS** [comment]
I’ll take a look.  What are your settings and what does your log look like
(primarily want to see script no version on startup if it gets there).

**Comment by Spillebulle** [comment]
> Your docker container just may be out of date, I've re-pulled just now and it launches without issue. I changed how the watchdog module gets imported about 3 weeks ago, and also added watchdog as a requirement in requirements.txt (that gets install on docker image creation).

I repulled mccloud/subgen:latest and ran again, still same error. Here are the envs:
![image](https://github.com/McCloudS/subgen/assets/46653946/2bb83ff9-7cc8-4769-a0fb-57f35a13656e)
